// Generated by purs version 0.15.16
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Array_NonEmpty_Internal from "../Data.Array.NonEmpty.Internal/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Data_String_CodeUnits from "../Data.String.CodeUnits/index.js";
import * as Data_String_Common from "../Data.String.Common/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
import * as PureScript_Backend_Optimizer_Codegen_Tco from "../PureScript.Backend.Optimizer.Codegen.Tco/index.js";
import * as PureScript_Backend_Optimizer_CoreFn from "../PureScript.Backend.Optimizer.CoreFn/index.js";
import * as PureScript_Backend_Optimizer_Syntax from "../PureScript.Backend.Optimizer.Syntax/index.js";
import * as Puruby_Printer from "../Puruby.Printer/index.js";
import * as Puruby_RubyAst from "../Puruby.RubyAst/index.js";
var show = /* #__PURE__ */ Data_Show.show(Data_Show.showInt);
var map = /* #__PURE__ */ Data_Functor.map(Data_Functor.functorArray);
var fromFoldable = /* #__PURE__ */ Data_Array.fromFoldable(Data_Array_NonEmpty_Internal.foldableNonEmptyArray);
var append1 = /* #__PURE__ */ Data_Semigroup.append(Data_Semigroup.semigroupArray);
var show1 = /* #__PURE__ */ Data_Show.show(Data_Show.showNumber);
var elem = /* #__PURE__ */ Data_Array.elem(Data_Eq.eqString);
var foldl = /* #__PURE__ */ Data_Foldable.foldl(Data_Foldable.foldableArray);
var foldr = /* #__PURE__ */ Data_Foldable.foldr(Data_Foldable.foldableArray);
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var fromFoldable1 = /* #__PURE__ */ Data_Array.fromFoldable(Data_Foldable.foldableArray);
var translateOperator2 = function (v) {
    return function (op) {
        return function (e1) {
            return function (e2) {
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpArrayIndex) {
                    return new Puruby_RubyAst.RubyDynamicIndexAccess(e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanAnd) {
                    return new Puruby_RubyAst.RubyBinOp("&&", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOr) {
                    return new Puruby_RubyAst.RubyBinOp("||", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringAppend) {
                    return new Puruby_RubyAst.RubyBinOp("+", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpEq) {
                    return new Puruby_RubyAst.RubyBinOp("==", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpNotEq) {
                    return new Puruby_RubyAst.RubyBinOp("!=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLt) {
                    return new Puruby_RubyAst.RubyBinOp("<", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLte) {
                    return new Puruby_RubyAst.RubyBinOp("<=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGt) {
                    return new Puruby_RubyAst.RubyBinOp(">", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGte) {
                    return new Puruby_RubyAst.RubyBinOp(">=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpAdd) {
                    return new Puruby_RubyAst.RubyBinOp("+", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpSubtract) {
                    return new Puruby_RubyAst.RubyBinOp("-", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpMultiply) {
                    return new Puruby_RubyAst.RubyBinOp("*", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpDivide) {
                    return new Puruby_RubyAst.RubyBinOp("/", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpEq) {
                    return new Puruby_RubyAst.RubyBinOp("==", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpNotEq) {
                    return new Puruby_RubyAst.RubyBinOp("!=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGt) {
                    return new Puruby_RubyAst.RubyBinOp(">", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGte) {
                    return new Puruby_RubyAst.RubyBinOp(">=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLt) {
                    return new Puruby_RubyAst.RubyBinOp("<", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLte) {
                    return new Puruby_RubyAst.RubyBinOp("<=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpAdd) {
                    return new Puruby_RubyAst.RubyBinOp("+", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpSubtract) {
                    return new Puruby_RubyAst.RubyBinOp("-", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpMultiply) {
                    return new Puruby_RubyAst.RubyBinOp("*", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberNum && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpDivide) {
                    return new Puruby_RubyAst.RubyBinOp("/", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpEq) {
                    return new Puruby_RubyAst.RubyBinOp("==", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpNotEq) {
                    return new Puruby_RubyAst.RubyBinOp("!=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGt) {
                    return new Puruby_RubyAst.RubyBinOp(">", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGte) {
                    return new Puruby_RubyAst.RubyBinOp(">=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLt) {
                    return new Puruby_RubyAst.RubyBinOp("<", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLte) {
                    return new Puruby_RubyAst.RubyBinOp("<=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpEq) {
                    return new Puruby_RubyAst.RubyBinOp("==", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpNotEq) {
                    return new Puruby_RubyAst.RubyBinOp("!=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGt) {
                    return new Puruby_RubyAst.RubyBinOp(">", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGte) {
                    return new Puruby_RubyAst.RubyBinOp(">=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLt) {
                    return new Puruby_RubyAst.RubyBinOp("<", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpCharOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLte) {
                    return new Puruby_RubyAst.RubyBinOp("<=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpEq) {
                    return new Puruby_RubyAst.RubyBinOp("==", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpNotEq) {
                    return new Puruby_RubyAst.RubyBinOp("!=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGt) {
                    return new Puruby_RubyAst.RubyBinOp(">", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpGte) {
                    return new Puruby_RubyAst.RubyBinOp(">=", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLt) {
                    return new Puruby_RubyAst.RubyBinOp("<", e1, e2);
                };
                if (op instanceof PureScript_Backend_Optimizer_Syntax.OpStringOrd && op.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpLte) {
                    return new Puruby_RubyAst.RubyBinOp("<=", e1, e2);
                };
                return new Puruby_RubyAst.RubyRaw("\"TODO: Op2\"");
            };
        };
    };
};
var translateOperator1 = function (modName) {
    return function (op) {
        return function (e) {
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIsTag) {
                return new Puruby_RubyAst.RubyBinOp("==", new Puruby_RubyAst.RubyIndexAccess(e, 0), new Puruby_RubyAst.RubyString(op.value0.value1));
            };
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpBooleanNot) {
                return new Puruby_RubyAst.RubyBinOp("!", new Puruby_RubyAst.RubyRaw(""), e);
            };
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntBitNot) {
                return new Puruby_RubyAst.RubyBinOp("~", new Puruby_RubyAst.RubyRaw(""), e);
            };
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpIntNegate) {
                return new Puruby_RubyAst.RubyBinOp("-", new Puruby_RubyAst.RubyRaw(""), e);
            };
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpNumberNegate) {
                return new Puruby_RubyAst.RubyBinOp("-", new Puruby_RubyAst.RubyRaw(""), e);
            };
            if (op instanceof PureScript_Backend_Optimizer_Syntax.OpArrayLength) {
                return new Puruby_RubyAst.RubyPropertyAccess(e, "length");
            };
            return new Puruby_RubyAst.RubyRaw("\"TODO: Op1\"");
        };
    };
};
var syntaxTag = function (v) {
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Var) {
        return "Var";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Local) {
        return "Local";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Lit) {
        return "Lit";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.App) {
        return "App";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Abs) {
        return "Abs";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.UncurriedApp) {
        return "UncurriedApp";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.UncurriedAbs) {
        return "UncurriedAbs";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectApp) {
        return "UncurriedEffectApp";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectAbs) {
        return "UncurriedEffectAbs";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Accessor) {
        return "Accessor";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Update) {
        return "Update";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.CtorSaturated) {
        return "CtorSaturated";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.CtorDef) {
        return "CtorDef";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.LetRec) {
        return "LetRec";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Let) {
        return "Let";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.EffectBind) {
        return "EffectBind";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.EffectPure) {
        return "EffectPure";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.EffectDefer) {
        return "EffectDefer";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Branch) {
        return "Branch";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.PrimOp) {
        return "PrimOp";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.PrimEffect) {
        return "PrimEffect";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.PrimUndefined) {
        return "PrimUndefined";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Fail) {
        return "Fail";
    };
    if (v instanceof PureScript_Backend_Optimizer_Syntax.Typed) {
        return "Typed";
    };
    throw new Error("Failed pattern match at Puruby.CodeGen (line 203, column 13 - line 227, column 23): " + [ v.constructor.name ]);
};
var sanitizeName = function (n) {
    var n$prime = Data_String_Common.replaceAll("$")("")(Data_String_Common.replaceAll("'")("_")(n));
    var isKeyword = function (x) {
        return x === "void" || (x === "class" || (x === "return" || (x === "const" || (x === "new" || (x === "throw" || (x === "catch" || (x === "try" || (x === "if" || (x === "else" || (x === "while" || (x === "for" || (x === "do" || (x === "switch" || (x === "case" || (x === "default" || (x === "break" || (x === "continue" || (x === "boolean" || (x === "byte" || (x === "char" || (x === "short" || (x === "int" || (x === "long" || (x === "float" || (x === "double" || (x === "true" || (x === "false" || (x === "null" || (x === "this" || (x === "super" || (x === "instanceof" || (x === "public" || (x === "protected" || (x === "private" || (x === "static" || (x === "final" || (x === "abstract" || (x === "interface" || (x === "implements" || (x === "extends" || (x === "package" || (x === "import" || (x === "throws" || (x === "enum" || (x === "assert" || (x === "strictfp" || (x === "native" || (x === "synchronized" || (x === "transient" || x === "volatile")))))))))))))))))))))))))))))))))))))))))))))))));
    };
    var $137 = isKeyword(n$prime);
    if ($137) {
        return "_" + n$prime;
    };
    return n$prime;
};
var localId = function (mbI) {
    return function (v) {
        if (mbI instanceof Data_Maybe.Just) {
            var n1 = Data_String_Common.replaceAll("'")("_")(mbI.value0);
            var n2 = Data_String_Common.replaceAll("$")("")(n1);
            return n2 + ("_" + show(v));
        };
        if (mbI instanceof Data_Maybe.Nothing) {
            return "v_" + show(v);
        };
        throw new Error("Failed pattern match at Puruby.CodeGen (line 23, column 3 - line 29, column 32): " + [ mbI.constructor.name ]);
    };
};
var isSelfCall = function (ident) {
    return function (v) {
        if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Local && v.value1.value0 instanceof Data_Maybe.Just) {
            return sanitizeName(v.value1.value0.value0) === ident;
        };
        return false;
    };
};
var extractUncurriedAbs = function (v) {
    if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Abs) {
        var thisArgs = map(function (v1) {
            return localId(v1.value0)(v1.value1);
        })(fromFoldable(v.value1.value0));
        var v1 = extractUncurriedAbs(v.value1.value1);
        if (v1 instanceof Data_Maybe.Just) {
            return new Data_Maybe.Just({
                args: append1(thisArgs)(v1.value0.args),
                body: v1.value0.body
            });
        };
        if (v1 instanceof Data_Maybe.Nothing) {
            return new Data_Maybe.Just({
                args: thisArgs,
                body: v.value1.value1
            });
        };
        throw new Error("Failed pattern match at Puruby.CodeGen (line 38, column 8 - line 40, column 47): " + [ v1.constructor.name ]);
    };
    if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.UncurriedAbs) {
        return new Data_Maybe.Just({
            args: map(function (v1) {
                return localId(v1.value0)(v1.value1);
            })(v.value1.value0),
            body: v.value1.value1
        });
    };
    if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Typed) {
        return extractUncurriedAbs(v.value1.value1);
    };
    return Data_Maybe.Nothing.value;
};
var translateExpr = function (modName) {
    return function (loopCtx) {
        return function (isTail) {
            return function (v) {
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Lit) {
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitString) {
                        return new Puruby_RubyAst.RubyString(v.value1.value0.value0);
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitInt) {
                        return new Puruby_RubyAst.RubyRaw(show(v.value1.value0.value0));
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitNumber) {
                        return new Puruby_RubyAst.RubyRaw(show1(v.value1.value0.value0));
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitBoolean) {
                        return new Puruby_RubyAst.RubyRaw((function () {
                            if (v.value1.value0.value0) {
                                return "true";
                            };
                            return "false";
                        })());
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitChar) {
                        return new Puruby_RubyAst.RubyString(Data_String_CodeUnits.singleton(v.value1.value0.value0));
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitArray) {
                        return new Puruby_RubyAst.RubyArray(map(translateExpr(modName)(loopCtx)(false))(v.value1.value0.value0));
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitRecord) {
                        return new Puruby_RubyAst.RubyHash(map(function (v1) {
                            return new Data_Tuple.Tuple(v1.value0, translateExpr(modName)(loopCtx)(false)(v1.value1));
                        })(v.value1.value0.value0));
                    };
                    throw new Error("Failed pattern match at Puruby.CodeGen (line 53, column 14 - line 60, column 109): " + [ v.value1.value0.constructor.name ]);
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.App) {
                    var flattenApp = function (v1) {
                        if (v1.value1 instanceof PureScript_Backend_Optimizer_Syntax.App) {
                            var res = flattenApp(v1.value1.value0);
                            return {
                                fn: res.fn,
                                args: append1(res.args)(fromFoldable(v1.value1.value1))
                            };
                        };
                        return {
                            fn: v1,
                            args: [  ]
                        };
                    };
                    var flat = flattenApp(new PureScript_Backend_Optimizer_Codegen_Tco.TcoExpr(v.value0, v.value1));
                    var isTcoCall = (function () {
                        if (flat.fn.value1 instanceof PureScript_Backend_Optimizer_Syntax.Var) {
                            var checkName = Data_String_Common.replaceAll("'")("_")(Data_String_Common.replaceAll("$")("")(flat.fn.value1.value0.value1));
                            return isTail && elem(checkName)(map(function (v1) {
                                return v1.ident;
                            })(loopCtx));
                        };
                        if (flat.fn.value1 instanceof PureScript_Backend_Optimizer_Syntax.Local && flat.fn.value1.value0 instanceof Data_Maybe.Just) {
                            return isTail && elem(localId(new Data_Maybe.Just(flat.fn.value1.value0.value0))(flat.fn.value1.value1))(map(function (v1) {
                                return v1.ident;
                            })(loopCtx));
                        };
                        return false;
                    })();
                    if (isTcoCall) {
                        var targetCtx = (function () {
                            if (flat.fn.value1 instanceof PureScript_Backend_Optimizer_Syntax.Var) {
                                var checkName = Data_String_Common.replaceAll("'")("_")(Data_String_Common.replaceAll("$")("")(flat.fn.value1.value0.value1));
                                return Data_Array.find(function (c) {
                                    return c.ident === checkName;
                                })(loopCtx);
                            };
                            if (flat.fn.value1 instanceof PureScript_Backend_Optimizer_Syntax.Local && flat.fn.value1.value0 instanceof Data_Maybe.Just) {
                                return Data_Array.find(function (c) {
                                    return c.ident === localId(new Data_Maybe.Just(flat.fn.value1.value0.value0))(flat.fn.value1.value1);
                                })(loopCtx);
                            };
                            return Data_Maybe.Nothing.value;
                        })();
                        if (targetCtx instanceof Data_Maybe.Just) {
                            return new Puruby_RubyAst.RubyContinue(targetCtx.value0.ident, map(function (arg) {
                                return translateExpr(modName)(loopCtx)(false)(arg);
                            })(flat.args));
                        };
                        if (targetCtx instanceof Data_Maybe.Nothing) {
                            return foldl(function (acc) {
                                return function (arg) {
                                    return new Puruby_RubyAst.RubyCall(acc, [ translateExpr(modName)(loopCtx)(false)(arg) ]);
                                };
                            })(translateExpr(modName)(loopCtx)(false)(v.value1.value0))(fromFoldable(v.value1.value1));
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 87, column 12 - line 91, column 156): " + [ targetCtx.constructor.name ]);
                    };
                    return foldl(function (acc) {
                        return function (arg) {
                            return new Puruby_RubyAst.RubyCall(acc, [ translateExpr(modName)(loopCtx)(false)(arg) ]);
                        };
                    })(translateExpr(modName)(loopCtx)(false)(v.value1.value0))(fromFoldable(v.value1.value1));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.UncurriedApp) {
                    return new Puruby_RubyAst.RubyCall(translateExpr(modName)(loopCtx)(false)(v.value1.value0), map(translateExpr(modName)(loopCtx)(false))(v.value1.value1));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectApp) {
                    return new Puruby_RubyAst.RubyThunk(new Puruby_RubyAst.RubyCall(translateExpr(modName)(loopCtx)(false)(v.value1.value0), map(translateExpr(modName)(loopCtx)(false))(v.value1.value1)));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.UncurriedAbs) {
                    return new Puruby_RubyAst.RubyUncurriedAbs(map(function (v1) {
                        if (v1.value0 instanceof Data_Maybe.Just) {
                            return sanitizeName(v1.value0.value0);
                        };
                        if (v1.value0 instanceof Data_Maybe.Nothing) {
                            return "__unused";
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 99, column 46 - line 101, column 28): " + [ v1.value0.constructor.name ]);
                    })(v.value1.value0), translateExpr(modName)(loopCtx)(false)(v.value1.value1));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectAbs) {
                    return new Puruby_RubyAst.RubyUncurriedAbs(map(function (v1) {
                        if (v1.value0 instanceof Data_Maybe.Just) {
                            return sanitizeName(v1.value0.value0);
                        };
                        if (v1.value0 instanceof Data_Maybe.Nothing) {
                            return "__unused";
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 103, column 46 - line 105, column 28): " + [ v1.value0.constructor.name ]);
                    })(v.value1.value0), translateExpr(modName)(loopCtx)(false)(v.value1.value1));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Accessor) {
                    if (v.value1.value1 instanceof PureScript_Backend_Optimizer_Syntax.GetProp) {
                        return new Puruby_RubyAst.RubyAccessor(translateExpr(modName)(loopCtx)(false)(v.value1.value0), v.value1.value1.value0);
                    };
                    if (v.value1.value1 instanceof PureScript_Backend_Optimizer_Syntax.GetIndex) {
                        return new Puruby_RubyAst.RubyIndexAccess(translateExpr(modName)(loopCtx)(false)(v.value1.value0), v.value1.value1.value0);
                    };
                    if (v.value1.value1 instanceof PureScript_Backend_Optimizer_Syntax.GetCtorField) {
                        return new Puruby_RubyAst.RubyIndexAccess(translateExpr(modName)(loopCtx)(false)(v.value1.value0), v.value1.value1.value5 + 1 | 0);
                    };
                    return new Puruby_RubyAst.RubyRaw("nil # TODO: Accessor");
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Update) {
                    return new Puruby_RubyAst.RubyRaw("nil");
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.PrimOp) {
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_Syntax.Op1) {
                        return translateOperator1(modName)(v.value1.value0.value0)(translateExpr(modName)(loopCtx)(false)(v.value1.value0.value1));
                    };
                    if (v.value1.value0 instanceof PureScript_Backend_Optimizer_Syntax.Op2) {
                        return translateOperator2(modName)(v.value1.value0.value0)(translateExpr(modName)(loopCtx)(false)(v.value1.value0.value1))(translateExpr(modName)(loopCtx)(false)(v.value1.value0.value2));
                    };
                    throw new Error("Failed pattern match at Puruby.CodeGen (line 116, column 16 - line 118, column 134): " + [ v.value1.value0.constructor.name ]);
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Var) {
                    var qModName = (function () {
                        if (v.value1.value0.value0 instanceof Data_Maybe.Just) {
                            return new Data_Maybe.Just(Data_String_Common.replaceAll(".")("_")(v.value1.value0.value0.value0));
                        };
                        if (v.value1.value0.value0 instanceof Data_Maybe.Nothing) {
                            return Data_Maybe.Nothing.value;
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 122, column 20 - line 124, column 29): " + [ v.value1.value0.value0.constructor.name ]);
                    })();
                    return new Puruby_RubyAst.RubyGlobalVar(qModName, sanitizeName(v.value1.value0.value1));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.PrimUndefined) {
                    return new Puruby_RubyAst.RubyRaw("nil");
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.App) {
                    var flattenApp = function (v1) {
                        if (v1.value1 instanceof PureScript_Backend_Optimizer_Syntax.App) {
                            var res = flattenApp(v1.value1.value0);
                            return {
                                fn: res.fn,
                                args: append1(res.args)(fromFoldable(v1.value1.value1))
                            };
                        };
                        return {
                            fn: v1,
                            args: [  ]
                        };
                    };
                    var flat = flattenApp(new PureScript_Backend_Optimizer_Codegen_Tco.TcoExpr(v.value0, v.value1));
                    if (isTail) {
                        var targetCtx = Data_Array.find(function (ctx) {
                            return isSelfCall(ctx.ident)(flat.fn);
                        })(loopCtx);
                        if (targetCtx instanceof Data_Maybe.Just) {
                            return new Puruby_RubyAst.RubyContinue(targetCtx.value0.ident, map(function (arg) {
                                return translateExpr(modName)(loopCtx)(false)(arg);
                            })(flat.args));
                        };
                        if (targetCtx instanceof Data_Maybe.Nothing) {
                            return foldl(function (acc) {
                                return function (arg) {
                                    return new Puruby_RubyAst.RubyCall(acc, [ translateExpr(modName)(loopCtx)(false)(arg) ]);
                                };
                            })(translateExpr(modName)(loopCtx)(false)(flat.fn))(flat.args);
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 137, column 12 - line 139, column 154): " + [ targetCtx.constructor.name ]);
                    };
                    return foldl(function (acc) {
                        return function (arg) {
                            return new Puruby_RubyAst.RubyCall(acc, [ translateExpr(modName)(loopCtx)(false)(arg) ]);
                        };
                    })(translateExpr(modName)(loopCtx)(false)(flat.fn))(flat.args);
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Abs) {
                    return foldr(function (v1) {
                        return function (acc) {
                            return new Puruby_RubyAst.RubyAbs([ localId(v1.value0)(v1.value1) ], acc);
                        };
                    })(translateExpr(modName)(loopCtx)(isTail)(v.value1.value1))(fromFoldable(v.value1.value0));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Let) {
                    return new Puruby_RubyAst.RubyLet(localId(v.value1.value0)(v.value1.value1), translateExpr(modName)(loopCtx)(false)(v.value1.value2), translateExpr(modName)(loopCtx)(isTail)(v.value1.value3));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.LetRec) {
                    var tcoInfo = unwrap(v.value0);
                    var $283 = tcoInfo.role.isLoop && Data_Array.length(fromFoldable(v.value1.value1)) === 1;
                    if ($283) {
                        var v1 = Data_Array.head(fromFoldable(v.value1.value1));
                        if (v1 instanceof Data_Maybe.Just) {
                            var javaName = localId(new Data_Maybe.Just(v1.value0.value0))(v.value1.value0);
                            var v2 = extractUncurriedAbs(v1.value0.value1);
                            if (v2 instanceof Data_Maybe.Just) {
                                var newCtx = {
                                    ident: javaName,
                                    params: v2.value0.args
                                };
                                var loopBody = translateExpr(modName)(Data_Array.snoc(loopCtx)(newCtx))(true)(v2.value0.body);
                                var curriedLoop = Data_Array.foldr(function (arg) {
                                    return function (acc) {
                                        return new Puruby_RubyAst.RubyAbs([ arg ], acc);
                                    };
                                })(new Puruby_RubyAst.RubyWhileTrue(v2.value0.args, loopBody))(v2.value0.args);
                                return new Puruby_RubyAst.RubyLet(javaName, curriedLoop, translateExpr(modName)(loopCtx)(isTail)(v.value1.value2));
                            };
                            if (v2 instanceof Data_Maybe.Nothing) {
                                return new Puruby_RubyAst.RubyLetRec([  ], new Puruby_RubyAst.RubyRaw("\"TODO: LetRec\""));
                            };
                            throw new Error("Failed pattern match at Puruby.CodeGen (line 156, column 16 - line 164, column 68): " + [ v2.constructor.name ]);
                        };
                        if (v1 instanceof Data_Maybe.Nothing) {
                            return new Puruby_RubyAst.RubyLetRec([  ], new Puruby_RubyAst.RubyRaw("\"TODO: LetRec\""));
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 152, column 9 - line 165, column 64): " + [ v1.constructor.name ]);
                    };
                    return new Puruby_RubyAst.RubyLetRec([  ], new Puruby_RubyAst.RubyRaw("\"TODO: LetRec\""));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Branch) {
                    var foldBranch = function (v1) {
                        return function (acc) {
                            return new Puruby_RubyAst.RubyTernary(translateExpr(modName)(loopCtx)(false)(v1.value0), translateExpr(modName)(loopCtx)(isTail)(v1.value1), acc);
                        };
                    };
                    return Data_Array.foldr(foldBranch)(translateExpr(modName)(loopCtx)(isTail)(v.value1.value1))(fromFoldable(v.value1.value0));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                    var varName = localId(v.value1.value0)(v.value1.value1);
                    var isLoopVar = Data_Array.any(function (ctx) {
                        return elem(varName)(ctx.params);
                    })(loopCtx);
                    return new Puruby_RubyAst.RubyLocal((function () {
                        if (isLoopVar) {
                            return "__tco_" + varName;
                        };
                        return varName;
                    })());
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.EffectBind) {
                    return new Puruby_RubyAst.RubyRaw("\"TODO: EffectBind\"");
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.EffectPure) {
                    return new Puruby_RubyAst.RubyThunk(translateExpr(modName)(loopCtx)(false)(v.value1.value0));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.EffectDefer) {
                    return new Puruby_RubyAst.RubyThunk(translateExpr(modName)(loopCtx)(false)(v.value1.value0));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Typed) {
                    return translateExpr(modName)(loopCtx)(isTail)(v.value1.value1);
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.CtorDef) {
                    var body = new Puruby_RubyAst.RubyArray(Data_Array.cons(new Puruby_RubyAst.RubyString(v.value1.value2))(map(function (arg) {
                        return new Puruby_RubyAst.RubyLocal(arg);
                    })(v.value1.value3)));
                    return foldr(function (arg) {
                        return function (acc) {
                            return new Puruby_RubyAst.RubyAbs([ arg ], acc);
                        };
                    })(body)(v.value1.value3);
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.CtorSaturated) {
                    return new Puruby_RubyAst.RubyArray(Data_Array.cons(new Puruby_RubyAst.RubyString(v.value1.value3))(map(function (v1) {
                        return translateExpr(modName)(loopCtx)(false)(v1.value1);
                    })(fromFoldable1(v.value1.value4))));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.Fail) {
                    return new Puruby_RubyAst.RubyRaw("raise(" + (Puruby_Printer.printExpr(new Puruby_RubyAst.RubyString(v.value1.value0)) + ")"));
                };
                if (v.value1 instanceof PureScript_Backend_Optimizer_Syntax.PrimEffect) {
                    return new Puruby_RubyAst.RubyThunk((function () {
                        if (v.value1.value0 instanceof PureScript_Backend_Optimizer_Syntax.EffectRefNew) {
                            return new Puruby_RubyAst.RubyHash([ new Data_Tuple.Tuple("value", translateExpr(modName)(loopCtx)(false)(v.value1.value0.value0)) ]);
                        };
                        if (v.value1.value0 instanceof PureScript_Backend_Optimizer_Syntax.EffectRefRead) {
                            return new Puruby_RubyAst.RubyDynamicIndexAccess(translateExpr(modName)(loopCtx)(false)(v.value1.value0.value0), new Puruby_RubyAst.RubyString("value"));
                        };
                        if (v.value1.value0 instanceof PureScript_Backend_Optimizer_Syntax.EffectRefWrite) {
                            return new Puruby_RubyAst.RubyIndexAssign(translateExpr(modName)(loopCtx)(false)(v.value1.value0.value0), new Puruby_RubyAst.RubyString("value"), translateExpr(modName)(loopCtx)(false)(v.value1.value0.value1));
                        };
                        throw new Error("Failed pattern match at Puruby.CodeGen (line 193, column 34 - line 199, column 127): " + [ v.value1.value0.constructor.name ]);
                    })());
                };
                return new Puruby_RubyAst.RubyRaw("\"TODO: " + (syntaxTag(v.value1) + "\""));
            };
        };
    };
};
var translate = function (mod) {
    var v = foldl(function (v1) {
        return function (group) {
            var tcoBinds = map(function (v2) {
                return new Data_Tuple.Tuple(v2.value0, PureScript_Backend_Optimizer_Codegen_Tco.analyze(v1.value0)(v2.value1));
            })(group.bindings);
            return new Data_Tuple.Tuple(v1.value0, Data_Array.snoc(v1.value1)({
                recursive: group.recursive,
                bindings: tcoBinds
            }));
        };
    })(new Data_Tuple.Tuple([  ], [  ]))(mod.bindings);
    var modNameStr = Data_String_Common.replaceAll(".")("_")(mod.name);
    var mainDecls = Data_Array.concatMap(function (group) {
        var $339 = group.recursive && Data_Array.length(group.bindings) === 1;
        if ($339) {
            var v1 = Data_Array.head(group.bindings);
            if (v1 instanceof Data_Maybe.Just) {
                var v2 = extractUncurriedAbs(v1.value0.value1);
                if (v2 instanceof Data_Maybe.Just) {
                    var javaName = sanitizeName(v1.value0.value0);
                    var newCtx = {
                        ident: javaName,
                        params: v2.value0.args
                    };
                    var loopBody = translateExpr(modNameStr)([ newCtx ])(true)(v2.value0.body);
                    var funcBody = new Puruby_RubyAst.RubyWhileTrue(v2.value0.args, loopBody);
                    return [ new Puruby_RubyAst.RubyAssign(modNameStr + ("_" + javaName), new Puruby_RubyAst.RubyAbs(v2.value0.args, funcBody)) ];
                };
                if (v2 instanceof Data_Maybe.Nothing) {
                    return [ new Puruby_RubyAst.RubyAssign(modNameStr + ("_" + sanitizeName(v1.value0.value0)), translateExpr(modNameStr)([  ])(false)(v1.value0.value1)) ];
                };
                throw new Error("Failed pattern match at Puruby.CodeGen (line 251, column 17 - line 261, column 115): " + [ v2.constructor.name ]);
            };
            if (v1 instanceof Data_Maybe.Nothing) {
                return [  ];
            };
            throw new Error("Failed pattern match at Puruby.CodeGen (line 249, column 13 - line 262, column 28): " + [ v1.constructor.name ]);
        };
        return map(function (v1) {
            return new Puruby_RubyAst.RubyAssign(modNameStr + ("_" + sanitizeName(v1.value0)), translateExpr(modNameStr)([  ])(false)(v1.value1));
        })(group.bindings);
    })(v.value1);
    var dataClasses = Data_Array.concatMap(function (decl) {
        return map(function (ctor) {
            var safeCtorName = Data_String_Common.replaceAll("'")("_prime_")(ctor.name);
            var args = Data_Array.mapWithIndex(function (i) {
                return function (v1) {
                    return "value" + show(i);
                };
            })(ctor.fields);
            return new Puruby_RubyAst.RubyRaw("");
        })(decl.constructors);
    })(mod.dataDecls);
    var decls = append1(dataClasses)(mainDecls);
    return {
        decls: decls
    };
};
export {
    localId,
    extractUncurriedAbs,
    isSelfCall,
    translateExpr,
    syntaxTag,
    translate,
    translateOperator1,
    translateOperator2,
    sanitizeName
};
//# sourceMappingURL=index.js.map
