// Generated by purs version 0.15.16
import * as Safe_Coerce from "../Safe.Coerce/index.js";
var coerce = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce1 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce2 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce3 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce4 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce5 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce6 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce7 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce8 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce9 = /* #__PURE__ */ Safe_Coerce.coerce();
var coerce10 = /* #__PURE__ */ Safe_Coerce.coerce();
var wrap = function () {
    return coerce;
};
var wrap1 = /* #__PURE__ */ wrap();
var wrap2 = /* #__PURE__ */ wrap();
var unwrap = function () {
    return coerce1;
};
var unwrap1 = /* #__PURE__ */ unwrap();
var unwrap2 = /* #__PURE__ */ unwrap();
var underF2 = function () {
    return function () {
        return function () {
            return function () {
                return function (v) {
                    return coerce2;
                };
            };
        };
    };
};
var underF = function () {
    return function () {
        return function () {
            return function () {
                return function (v) {
                    return coerce3;
                };
            };
        };
    };
};
var under2 = function () {
    return function () {
        return function (v) {
            return coerce4;
        };
    };
};
var under = function () {
    return function () {
        return function (v) {
            return coerce5;
        };
    };
};
var un = function () {
    return function (v) {
        return unwrap1;
    };
};
var traverse = function () {
    return function () {
        return function (v) {
            return coerce6;
        };
    };
};
var overF2 = function () {
    return function () {
        return function () {
            return function () {
                return function (v) {
                    return coerce2;
                };
            };
        };
    };
};
var overF = function () {
    return function () {
        return function () {
            return function () {
                return function (v) {
                    return coerce3;
                };
            };
        };
    };
};
var over2 = function () {
    return function () {
        return function (v) {
            return coerce7;
        };
    };
};
var over = function () {
    return function () {
        return function (v) {
            return coerce8;
        };
    };
};
var newtypeMultiplicative = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeLast = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeFirst = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeEndo = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeDual = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeDisj = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeConj = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeAdditive = {
    Coercible0: function () {
        return undefined;
    }
};
var modify = function () {
    return function (fn) {
        return function (t) {
            return wrap1(fn(unwrap2(t)));
        };
    };
};
var collect = function () {
    return function () {
        return function (v) {
            return coerce9;
        };
    };
};
var alaF = function () {
    return function () {
        return function () {
            return function () {
                return function (v) {
                    return coerce3;
                };
            };
        };
    };
};
var ala = function () {
    return function () {
        return function () {
            return function (v) {
                return function (f) {
                    return coerce10(f(wrap2));
                };
            };
        };
    };
};
export {
    wrap,
    unwrap,
    un,
    modify,
    ala,
    alaF,
    over,
    overF,
    under,
    underF,
    over2,
    overF2,
    under2,
    underF2,
    traverse,
    collect,
    newtypeAdditive,
    newtypeMultiplicative,
    newtypeConj,
    newtypeDisj,
    newtypeDual,
    newtypeEndo,
    newtypeFirst,
    newtypeLast
};
//# sourceMappingURL=index.js.map
