// Generated by purs version 0.15.16
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Array_NonEmpty from "../Data.Array.NonEmpty/index.js";
import * as Data_Array_NonEmpty_Internal from "../Data.Array.NonEmpty.Internal/index.js";
import * as Data_Boolean from "../Data.Boolean/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Map_Internal from "../Data.Map.Internal/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Monoid from "../Data.Monoid/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Ordering from "../Data.Ordering/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Set from "../Data.Set/index.js";
import * as Data_String_CodeUnits from "../Data.String.CodeUnits/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
import * as PureScript_Backend_Optimizer_CoreFn from "../PureScript.Backend.Optimizer.CoreFn/index.js";
import * as PureScript_Backend_Optimizer_Syntax from "../PureScript.Backend.Optimizer.Syntax/index.js";
var union = /* #__PURE__ */ Data_Set.union(Data_Ord.ordInt);
var unionWith = /* #__PURE__ */ Data_Map_Internal.unionWith(PureScript_Backend_Optimizer_Syntax.ordLevel);
var ordQualified = /* #__PURE__ */ PureScript_Backend_Optimizer_CoreFn.ordQualified(PureScript_Backend_Optimizer_CoreFn.ordIdent);
var union1 = /* #__PURE__ */ Data_Set.union(ordQualified);
var insert = /* #__PURE__ */ Data_Set.insert(ordQualified);
var update = /* #__PURE__ */ Data_Map_Internal.update(PureScript_Backend_Optimizer_Syntax.ordLevel);
var over = /* #__PURE__ */ Data_Newtype.over()();
var map = /* #__PURE__ */ Data_Functor.map(Data_Map_Internal.functorMap);
var insert1 = /* #__PURE__ */ Data_Set.insert(Data_Ord.ordInt);
var pop = /* #__PURE__ */ Data_Map_Internal.pop(PureScript_Backend_Optimizer_Syntax.ordLevel);
var $$delete = /* #__PURE__ */ Data_Map_Internal["delete"](PureScript_Backend_Optimizer_Syntax.ordLevel);
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var foldMap = /* #__PURE__ */ Data_Foldable.foldMap(Data_Array_NonEmpty_Internal.foldableNonEmptyArray);
var foldr = /* #__PURE__ */ Data_Foldable.foldr(Data_Array_NonEmpty_Internal.foldableNonEmptyArray);
var foldr1 = /* #__PURE__ */ Data_Foldable.foldr(Data_Foldable.foldableArray);
var KnownNeutral = /* #__PURE__ */ (function () {
    function KnownNeutral() {

    };
    KnownNeutral.value = new KnownNeutral();
    return KnownNeutral;
})();
var Unknown = /* #__PURE__ */ (function () {
    function Unknown() {

    };
    Unknown.value = new Unknown();
    return Unknown;
})();
var Trivial = /* #__PURE__ */ (function () {
    function Trivial() {

    };
    Trivial.value = new Trivial();
    return Trivial;
})();
var Deref = /* #__PURE__ */ (function () {
    function Deref() {

    };
    Deref.value = new Deref();
    return Deref;
})();
var KnownSize = /* #__PURE__ */ (function () {
    function KnownSize() {

    };
    KnownSize.value = new KnownSize();
    return KnownSize;
})();
var NonTrivial = /* #__PURE__ */ (function () {
    function NonTrivial() {

    };
    NonTrivial.value = new NonTrivial();
    return NonTrivial;
})();
var CaptureNone = /* #__PURE__ */ (function () {
    function CaptureNone() {

    };
    CaptureNone.value = new CaptureNone();
    return CaptureNone;
})();
var CaptureBranch = /* #__PURE__ */ (function () {
    function CaptureBranch() {

    };
    CaptureBranch.value = new CaptureBranch();
    return CaptureBranch;
})();
var CaptureClosure = /* #__PURE__ */ (function () {
    function CaptureClosure() {

    };
    CaptureClosure.value = new CaptureClosure();
    return CaptureClosure;
})();
var Usage = function (x) {
    return x;
};
var BackendAnalysis = function (x) {
    return x;
};
var semigroupResultTerm = {
    append: function (v) {
        return function (v1) {
            if (v instanceof Unknown) {
                return Unknown.value;
            };
            if (v1 instanceof Unknown) {
                return Unknown.value;
            };
            return KnownNeutral.value;
        };
    }
};
var append = /* #__PURE__ */ Data_Semigroup.append(semigroupResultTerm);
var newtypeUsage_ = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeBackendAnalysis_ = {
    Coercible0: function () {
        return undefined;
    }
};
var monoidResultTerm = /* #__PURE__ */ (function () {
    return {
        mempty: KnownNeutral.value,
        Semigroup0: function () {
            return semigroupResultTerm;
        }
    };
})();
var foldMap1 = /* #__PURE__ */ foldMap(monoidResultTerm);
var eqResultTerm = {
    eq: function (x) {
        return function (y) {
            if (x instanceof KnownNeutral && y instanceof KnownNeutral) {
                return true;
            };
            if (x instanceof Unknown && y instanceof Unknown) {
                return true;
            };
            return false;
        };
    }
};
var eqComplexity = {
    eq: function (x) {
        return function (y) {
            if (x instanceof Trivial && y instanceof Trivial) {
                return true;
            };
            if (x instanceof Deref && y instanceof Deref) {
                return true;
            };
            if (x instanceof KnownSize && y instanceof KnownSize) {
                return true;
            };
            if (x instanceof NonTrivial && y instanceof NonTrivial) {
                return true;
            };
            return false;
        };
    }
};
var ordComplexity = {
    compare: function (x) {
        return function (y) {
            if (x instanceof Trivial && y instanceof Trivial) {
                return Data_Ordering.EQ.value;
            };
            if (x instanceof Trivial) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof Trivial) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof Deref && y instanceof Deref) {
                return Data_Ordering.EQ.value;
            };
            if (x instanceof Deref) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof Deref) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof KnownSize && y instanceof KnownSize) {
                return Data_Ordering.EQ.value;
            };
            if (x instanceof KnownSize) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof KnownSize) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof NonTrivial && y instanceof NonTrivial) {
                return Data_Ordering.EQ.value;
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 0, column 0 - line 0, column 0): " + [ x.constructor.name, y.constructor.name ]);
        };
    },
    Eq0: function () {
        return eqComplexity;
    }
};
var semigroupComplexity = {
    append: /* #__PURE__ */ Data_Ord.max(ordComplexity)
};
var append1 = /* #__PURE__ */ Data_Semigroup.append(semigroupComplexity);
var monoidComplexity = /* #__PURE__ */ (function () {
    return {
        mempty: Trivial.value,
        Semigroup0: function () {
            return semigroupComplexity;
        }
    };
})();
var eqCapture = {
    eq: function (x) {
        return function (y) {
            if (x instanceof CaptureNone && y instanceof CaptureNone) {
                return true;
            };
            if (x instanceof CaptureBranch && y instanceof CaptureBranch) {
                return true;
            };
            if (x instanceof CaptureClosure && y instanceof CaptureClosure) {
                return true;
            };
            return false;
        };
    }
};
var ordCapture = {
    compare: function (x) {
        return function (y) {
            if (x instanceof CaptureNone && y instanceof CaptureNone) {
                return Data_Ordering.EQ.value;
            };
            if (x instanceof CaptureNone) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof CaptureNone) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof CaptureBranch && y instanceof CaptureBranch) {
                return Data_Ordering.EQ.value;
            };
            if (x instanceof CaptureBranch) {
                return Data_Ordering.LT.value;
            };
            if (y instanceof CaptureBranch) {
                return Data_Ordering.GT.value;
            };
            if (x instanceof CaptureClosure && y instanceof CaptureClosure) {
                return Data_Ordering.EQ.value;
            };
            throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 0, column 0 - line 0, column 0): " + [ x.constructor.name, y.constructor.name ]);
        };
    },
    Eq0: function () {
        return eqCapture;
    }
};
var semigroupCapture = {
    append: /* #__PURE__ */ Data_Ord.max(ordCapture)
};
var append2 = /* #__PURE__ */ Data_Semigroup.append(semigroupCapture);
var monoidCapture = /* #__PURE__ */ (function () {
    return {
        mempty: CaptureNone.value,
        Semigroup0: function () {
            return semigroupCapture;
        }
    };
})();
var mempty = /* #__PURE__ */ Data_Monoid.mempty(monoidCapture);
var semigroupUsage = {
    append: function (v) {
        return function (v1) {
            return {
                total: v.total + v1.total | 0,
                captured: append2(v.captured)(v1.captured),
                arities: union(v.arities)(v1.arities),
                call: v.call + v1.call | 0,
                access: v.access + v1.access | 0,
                "case": v["case"] + v1["case"] | 0,
                update: v.update + v1.update | 0
            };
        };
    }
};
var append3 = /* #__PURE__ */ Data_Semigroup.append(semigroupUsage);
var monoidUsage = {
    mempty: {
        total: 0,
        captured: mempty,
        arities: Data_Set.empty,
        call: 0,
        access: 0,
        "case": 0,
        update: 0
    },
    Semigroup0: function () {
        return semigroupUsage;
    }
};
var mempty1 = /* #__PURE__ */ Data_Monoid.mempty(monoidUsage);
var semigroupBackendAnalysis = {
    append: function (v) {
        return function (v1) {
            return {
                usages: unionWith(append3)(v.usages)(v1.usages),
                size: v.size + v1.size | 0,
                complexity: append1(v.complexity)(v1.complexity),
                args: [  ],
                rewrite: v.rewrite || v1.rewrite,
                deps: union1(v.deps)(v1.deps),
                result: append(v.result)(v1.result),
                externs: v.externs || v1.externs
            };
        };
    }
};
var append4 = /* #__PURE__ */ Data_Semigroup.append(semigroupBackendAnalysis);
var monoidBackendAnalysis = /* #__PURE__ */ (function () {
    return {
        mempty: {
            usages: Data_Map_Internal.empty,
            size: 0,
            complexity: Trivial.value,
            args: [  ],
            rewrite: false,
            deps: Data_Set.empty,
            result: KnownNeutral.value,
            externs: false
        },
        Semigroup0: function () {
            return semigroupBackendAnalysis;
        }
    };
})();
var mempty2 = /* #__PURE__ */ Data_Monoid.mempty(monoidBackendAnalysis);
var foldMap2 = /* #__PURE__ */ Data_Foldable.foldMap(PureScript_Backend_Optimizer_Syntax.foldableBackendSyntax)(monoidBackendAnalysis);
var mempty3 = /* #__PURE__ */ Data_Monoid.mempty(monoidBackendAnalysis);
var foldMap3 = /* #__PURE__ */ foldMap(monoidBackendAnalysis);
var foldMap4 = /* #__PURE__ */ Data_Foldable.foldMap(Data_Foldable.foldableArray)(monoidBackendAnalysis);
var foldMap5 = /* #__PURE__ */ Data_Foldable.foldMap(Data_Foldable.foldableTuple)(monoidBackendAnalysis);
var foldMap6 = /* #__PURE__ */ Data_Foldable.foldMap(PureScript_Backend_Optimizer_Syntax.foldablePair)(monoidBackendAnalysis);
var withRewrite = function (v) {
    return {
        usages: v.usages,
        size: v.size,
        complexity: v.complexity,
        args: v.args,
        deps: v.deps,
        result: v.result,
        externs: v.externs,
        rewrite: true
    };
};
var withResult = function (r) {
    return function (v) {
        return {
            usages: v.usages,
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            externs: v.externs,
            result: r
        };
    };
};
var withArgs = function (args) {
    return function (v) {
        return {
            usages: v.usages,
            size: v.size,
            complexity: v.complexity,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            args: args
        };
    };
};
var usedDep = function (dep) {
    return function (v) {
        return {
            usages: v.usages,
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            result: v.result,
            externs: v.externs,
            deps: insert(dep)(v.deps)
        };
    };
};
var used = function (level) {
    return {
        size: mempty2.size,
        complexity: mempty2.complexity,
        args: mempty2.args,
        rewrite: mempty2.rewrite,
        deps: mempty2.deps,
        result: mempty2.result,
        externs: mempty2.externs,
        usages: Data_Map_Internal.singleton(level)({
            total: 1,
            captured: mempty,
            arities: Data_Set.empty,
            call: 0,
            access: 0,
            "case": 0,
            update: 0
        })
    };
};
var updated = function (level) {
    return function (v) {
        return {
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            usages: update((function () {
                var $332 = over(Usage)(function (us) {
                    return {
                        access: us.access,
                        arities: us.arities,
                        call: us.call,
                        captured: us.captured,
                        "case": us["case"],
                        total: us.total,
                        update: us.update + 1 | 0
                    };
                });
                return function ($333) {
                    return Data_Maybe.Just.create($332($333));
                };
            })())(level)(v.usages)
        };
    };
};
var externs = function (v) {
    return {
        usages: v.usages,
        size: v.size,
        complexity: v.complexity,
        args: v.args,
        rewrite: v.rewrite,
        deps: v.deps,
        result: v.result,
        externs: true
    };
};
var complex = function (complexity) {
    return function (v) {
        return {
            usages: v.usages,
            size: v.size,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            complexity: append1(v.complexity)(complexity)
        };
    };
};
var cased = function (level) {
    return function (v) {
        return {
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            usages: update((function () {
                var $334 = over(Usage)(function (us) {
                    return {
                        access: us.access,
                        arities: us.arities,
                        call: us.call,
                        captured: us.captured,
                        total: us.total,
                        update: us.update,
                        "case": us["case"] + 1 | 0
                    };
                });
                return function ($335) {
                    return Data_Maybe.Just.create($334($335));
                };
            })())(level)(v.usages)
        };
    };
};
var capture = function (cap) {
    return function (v) {
        return {
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            usages: map(over(Usage)(function (v2) {
                return {
                    access: v2.access,
                    arities: v2.arities,
                    call: v2.call,
                    "case": v2["case"],
                    total: v2.total,
                    update: v2.update,
                    captured: cap
                };
            }))(v.usages)
        };
    };
};
var callArity = function (lvl) {
    return function (arity) {
        return function (v) {
            return {
                size: v.size,
                complexity: v.complexity,
                args: v.args,
                rewrite: v.rewrite,
                deps: v.deps,
                result: v.result,
                externs: v.externs,
                usages: update((function () {
                    var $336 = over(Usage)(function (us) {
                        return {
                            access: us.access,
                            captured: us.captured,
                            "case": us["case"],
                            total: us.total,
                            update: us.update,
                            arities: insert1(arity)(us.arities),
                            call: us.call + 1 | 0
                        };
                    });
                    return function ($337) {
                        return Data_Maybe.Just.create($336($337));
                    };
                })())(lvl)(v.usages)
            };
        };
    };
};
var bump = function (v) {
    return {
        usages: v.usages,
        complexity: v.complexity,
        args: v.args,
        rewrite: v.rewrite,
        deps: v.deps,
        result: v.result,
        externs: v.externs,
        size: v.size + 1 | 0
    };
};
var boundArg = function (level) {
    return function (v) {
        var v1 = pop(level)(v.usages);
        if (v1 instanceof Data_Maybe.Nothing) {
            return {
                usages: v.usages,
                size: v.size,
                complexity: v.complexity,
                rewrite: v.rewrite,
                deps: v.deps,
                result: v.result,
                externs: v.externs,
                args: Data_Array.cons(mempty1)(v.args)
            };
        };
        if (v1 instanceof Data_Maybe.Just) {
            return {
                size: v.size,
                complexity: v.complexity,
                rewrite: v.rewrite,
                deps: v.deps,
                result: v.result,
                externs: v.externs,
                usages: v1.value0.value1,
                args: Data_Array.cons(v1.value0.value0)(v.args)
            };
        };
        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 129, column 38 - line 133, column 66): " + [ v1.constructor.name ]);
    };
};
var bound = function (level) {
    return function (v) {
        return {
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            usages: $$delete(level)(v.usages)
        };
    };
};
var analysisOf = function (dict) {
    return dict.analysisOf;
};
var analyzeDefault = function (dictHasAnalysis) {
    var $338 = foldMap2(analysisOf(dictHasAnalysis));
    return function ($339) {
        return bump($338($339));
    };
};
var resultOf = function (dictHasAnalysis) {
    var $340 = analysisOf(dictHasAnalysis);
    return function ($341) {
        return (function (v) {
            return v.result;
        })(unwrap($340($341)));
    };
};
var accessed = function (level) {
    return function (v) {
        return {
            size: v.size,
            complexity: v.complexity,
            args: v.args,
            rewrite: v.rewrite,
            deps: v.deps,
            result: v.result,
            externs: v.externs,
            usages: update((function () {
                var $342 = over(Usage)(function (us) {
                    return {
                        arities: us.arities,
                        call: us.call,
                        captured: us.captured,
                        "case": us["case"],
                        total: us.total,
                        update: us.update,
                        access: us.access + 1 | 0
                    };
                });
                return function ($343) {
                    return Data_Maybe.Just.create($342($343));
                };
            })())(level)(v.usages)
        };
    };
};
var analyze = function (dictHasAnalysis) {
    var resultOf1 = resultOf(dictHasAnalysis);
    var analysisOf1 = analysisOf(dictHasAnalysis);
    var analysisOf2 = analysisOf(dictHasAnalysis);
    var analyzeDefault1 = analyzeDefault(dictHasAnalysis);
    var resultOf2 = resultOf(dictHasAnalysis);
    return function (dictHasSyntax) {
        var syntaxOf = PureScript_Backend_Optimizer_Syntax.syntaxOf(dictHasSyntax);
        return function (externAnalysis) {
            return function (expr) {
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Var) {
                    var analysis = bump(externs(usedDep(expr.value0)(mempty3)));
                    var v = externAnalysis(expr.value0)(Data_Maybe.Nothing.value);
                    if (v instanceof Data_Maybe.Just) {
                        return withArgs(v.value0.args)(analysis);
                    };
                    if (v instanceof Data_Maybe.Nothing) {
                        return analysis;
                    };
                    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 206, column 5 - line 210, column 17): " + [ v.constructor.name ]);
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                    return bump(used(expr.value1));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Let) {
                    return withResult(resultOf1(expr.value3))(bump(complex(NonTrivial.value)(append4(analysisOf1(expr.value2))(bound(expr.value1)(analysisOf1(expr.value3))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.LetRec) {
                    return withResult(resultOf1(expr.value2))(complex(NonTrivial.value)(bound(expr.value0)(bump(append4(foldMap3(function ($344) {
                        return analysisOf2(Data_Tuple.snd($344));
                    })(expr.value1))(analysisOf1(expr.value2))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectBind) {
                    return withResult(Unknown.value)(complex(NonTrivial.value)(capture(CaptureClosure.value)(bump(append4(analysisOf1(expr.value2))(bound(expr.value1)(analysisOf1(expr.value3)))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectPure) {
                    return withResult(Unknown.value)(capture(CaptureClosure.value)(bump(analysisOf1(expr.value0))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectDefer) {
                    return withResult(Unknown.value)(capture(CaptureClosure.value)(bump(analysisOf1(expr.value0))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Abs) {
                    return withResult(KnownNeutral.value)(complex(KnownSize.value)(capture(CaptureClosure.value)(foldr(function ($345) {
                        return boundArg(Data_Tuple.snd($345));
                    })(analyzeDefault1(expr))(expr.value0))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.UncurriedAbs) {
                    return withResult(KnownNeutral.value)(complex(KnownSize.value)(capture(CaptureClosure.value)(foldr1(function ($346) {
                        return boundArg(Data_Tuple.snd($346));
                    })(analyzeDefault1(expr))(expr.value0))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.UncurriedApp) {
                    var analysis = withResult(Unknown.value)(complex(NonTrivial.value)(analyzeDefault1(expr)));
                    var v = syntaxOf(expr.value0);
                    if (v instanceof Data_Maybe.Just && v.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                        return callArity(v.value0.value1)(Data_Array.length(expr.value1))(analysis);
                    };
                    return analysis;
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectAbs) {
                    return withResult(KnownNeutral.value)(complex(KnownSize.value)(capture(CaptureClosure.value)(foldr1(function ($347) {
                        return boundArg(Data_Tuple.snd($347));
                    })(analyzeDefault1(expr))(expr.value0))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectApp) {
                    var analysis = withResult(Unknown.value)(complex(NonTrivial.value)(capture(CaptureClosure.value)(analyzeDefault1(expr))));
                    var v = syntaxOf(expr.value0);
                    if (v instanceof Data_Maybe.Just && v.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                        return callArity(v.value0.value1)(Data_Array.length(expr.value1))(analysis);
                    };
                    return analysis;
                };
                var v = function (v1) {
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Update) {
                        var analysis = withResult(Unknown.value)(complex(NonTrivial.value)(analyzeDefault1(expr)));
                        var v2 = syntaxOf(expr.value0);
                        if (v2 instanceof Data_Maybe.Just && v2.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                            return updated(v2.value0.value1)(analysis);
                        };
                        return analysis;
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.CtorSaturated) {
                        return withResult(KnownNeutral.value)(bump(usedDep(expr.value0)(foldMap4(foldMap5(analysisOf2))(expr.value4))));
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.CtorDef) {
                        return complex(NonTrivial.value)(analyzeDefault1(expr));
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Branch) {
                        var v2 = Data_Array_NonEmpty.head(expr.value0);
                        var result = foldMap1(function ($348) {
                            return resultOf2(PureScript_Backend_Optimizer_Syntax.sndPair($348));
                        })(expr.value0);
                        return withResult(result)(complex(NonTrivial.value)(append4(analysisOf1(v2.value0))(append4(capture(CaptureBranch.value)(analysisOf1(v2.value1)))(append4(capture(CaptureBranch.value)(foldMap4(foldMap6(analysisOf2))(Data_Array_NonEmpty.tail(expr.value0))))(capture(CaptureBranch.value)(analysisOf1(expr.value1)))))));
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Fail) {
                        return complex(NonTrivial.value)(analyzeDefault1(expr));
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.PrimOp) {
                        var analysis = withResult(Unknown.value)(complex(NonTrivial.value)(analyzeDefault1(expr)));
                        var v2 = function (v3) {
                            if (expr.value0 instanceof PureScript_Backend_Optimizer_Syntax.Op1 && (expr.value0.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpIsTag && Data_Boolean.otherwise)) {
                                return usedDep(expr.value0.value0.value0)(analysis);
                            };
                            return analysis;
                        };
                        if (expr.value0 instanceof PureScript_Backend_Optimizer_Syntax.Op1 && expr.value0.value0 instanceof PureScript_Backend_Optimizer_Syntax.OpIsTag) {
                            var $261 = syntaxOf(expr.value0.value1);
                            if ($261 instanceof Data_Maybe.Just && $261.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                                return cased($261.value0.value1)(usedDep(expr.value0.value0.value0)(analysis));
                            };
                            return v2(true);
                        };
                        return v2(true);
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.PrimEffect) {
                        return withResult(Unknown.value)(complex(NonTrivial.value)(capture(CaptureClosure.value)(analyzeDefault1(expr))));
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.PrimUndefined) {
                        return analyzeDefault1(expr);
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Accessor) {
                        var analysis = (function () {
                            if (expr.value1 instanceof PureScript_Backend_Optimizer_Syntax.GetCtorField) {
                                return withResult(Unknown.value)(usedDep(expr.value1.value0)(analyzeDefault1(expr)));
                            };
                            return withResult(Unknown.value)(analyzeDefault1(expr));
                        })();
                        var v2 = syntaxOf(expr.value0);
                        if (v2 instanceof Data_Maybe.Just && v2.value0 instanceof PureScript_Backend_Optimizer_Syntax.Accessor) {
                            return analysis;
                        };
                        if (v2 instanceof Data_Maybe.Just && v2.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                            return accessed(v2.value0.value1)(complex(Deref.value)(analysis));
                        };
                        if (v2 instanceof Data_Maybe.Just && v2.value0 instanceof PureScript_Backend_Optimizer_Syntax.Var) {
                            var v3 = function (v4) {
                                return complex(Trivial.value)(analysis);
                            };
                            if (expr.value1 instanceof PureScript_Backend_Optimizer_Syntax.GetProp) {
                                var $285 = externAnalysis(v2.value0.value0)(new Data_Maybe.Just(expr.value1.value0));
                                if ($285 instanceof Data_Maybe.Just) {
                                    return withArgs($285.value0.args)(complex(Trivial.value)(analysis));
                                };
                                return v3(true);
                            };
                            return v3(true);
                        };
                        return complex(Deref.value)(analysis);
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Lit) {
                        var analysis = withResult(KnownNeutral.value)(analyzeDefault1(expr));
                        if (expr.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitArray && Data_Array.length(expr.value0.value0) > 0) {
                            return complex(KnownSize.value)(analysis);
                        };
                        if (expr.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitRecord) {
                            if (Data_Array.length(expr.value0.value0) > 0) {
                                return complex(KnownSize.value)(analysis);
                            };
                            if (Data_Boolean.otherwise) {
                                return analysis;
                            };
                        };
                        if (expr.value0 instanceof PureScript_Backend_Optimizer_CoreFn.LitString && Data_String_CodeUnits.length(expr.value0.value0) > 128) {
                            return complex(KnownSize.value)(analysis);
                        };
                        return analysis;
                    };
                    if (expr instanceof PureScript_Backend_Optimizer_Syntax.Typed) {
                        return analysisOf1(expr.value1);
                    };
                    throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 203, column 1 - line 203, column 150): " + [ expr.constructor.name ]);
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.App) {
                    var $301 = analysisOf1(expr.value0);
                    var remainingArgs = Data_Array.drop(Data_Array_NonEmpty.length(expr.value1))($301.args);
                    var analysis = (function () {
                        if (Data_Array["null"](remainingArgs)) {
                            return complex(NonTrivial.value)(analyzeDefault1(expr));
                        };
                        if (Data_Boolean.otherwise) {
                            return analyzeDefault1(expr);
                        };
                        throw new Error("Failed pattern match at PureScript.Backend.Optimizer.Analysis (line 298, column 5 - line 302, column 30): " + [  ]);
                    })();
                    return withArgs(remainingArgs)((function () {
                        var v1 = syntaxOf(expr.value0);
                        if (v1 instanceof Data_Maybe.Just && v1.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                            return withResult(Unknown.value)(callArity(v1.value0.value1)(Data_Array_NonEmpty.length(expr.value1))(bump(analysis)));
                        };
                        return withResult(Unknown.value)(bump(analysis));
                    })());
                };
                return v(true);
            };
        };
    };
};
var analyzeEffectBlock = function (dictHasAnalysis) {
    var resultOf1 = resultOf(dictHasAnalysis);
    var analysisOf1 = analysisOf(dictHasAnalysis);
    var analysisOf2 = analysisOf(dictHasAnalysis);
    var analyzeDefault1 = analyzeDefault(dictHasAnalysis);
    var analyze1 = analyze(dictHasAnalysis);
    return function (dictHasSyntax) {
        var syntaxOf = PureScript_Backend_Optimizer_Syntax.syntaxOf(dictHasSyntax);
        var analyze2 = analyze1(dictHasSyntax);
        return function (externAnalysis) {
            return function (expr) {
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Let) {
                    return withResult(resultOf1(expr.value3))(complex(NonTrivial.value)(bump(append4(analysisOf1(expr.value2))(bound(expr.value1)(analysisOf1(expr.value3))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.LetRec) {
                    return withResult(resultOf1(expr.value2))(complex(NonTrivial.value)(bound(expr.value0)(bump(append4(foldMap3(function ($349) {
                        return analysisOf2(Data_Tuple.snd($349));
                    })(expr.value1))(analysisOf1(expr.value2))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectBind) {
                    return withResult(Unknown.value)(complex(NonTrivial.value)(bump(append4(analysisOf1(expr.value2))(bound(expr.value1)(analysisOf1(expr.value3))))));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectPure) {
                    return withResult(Unknown.value)(bump(analysisOf1(expr.value0)));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.EffectDefer) {
                    return withResult(Unknown.value)(bump(analysisOf1(expr.value0)));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.UncurriedEffectApp) {
                    var analysis = withResult(Unknown.value)(complex(NonTrivial.value)(analyzeDefault1(expr)));
                    var v = syntaxOf(expr.value0);
                    if (v instanceof Data_Maybe.Just && v.value0 instanceof PureScript_Backend_Optimizer_Syntax.Local) {
                        return callArity(v.value0.value1)(Data_Array.length(expr.value1))(analysis);
                    };
                    return analysis;
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.PrimEffect) {
                    return withResult(Unknown.value)(complex(NonTrivial.value)(analyzeDefault1(expr)));
                };
                if (expr instanceof PureScript_Backend_Optimizer_Syntax.Typed) {
                    return analysisOf1(expr.value1);
                };
                return analyze2(externAnalysis)(expr);
            };
        };
    };
};
export {
    analysisOf,
    CaptureNone,
    CaptureBranch,
    CaptureClosure,
    Usage,
    Trivial,
    Deref,
    KnownSize,
    NonTrivial,
    KnownNeutral,
    Unknown,
    BackendAnalysis,
    bound,
    boundArg,
    withArgs,
    withRewrite,
    used,
    accessed,
    cased,
    updated,
    usedDep,
    bump,
    complex,
    capture,
    callArity,
    withResult,
    externs,
    resultOf,
    analyze,
    analyzeEffectBlock,
    analyzeDefault,
    eqCapture,
    ordCapture,
    semigroupCapture,
    monoidCapture,
    newtypeUsage_,
    semigroupUsage,
    monoidUsage,
    eqComplexity,
    ordComplexity,
    semigroupComplexity,
    monoidComplexity,
    eqResultTerm,
    semigroupResultTerm,
    monoidResultTerm,
    newtypeBackendAnalysis_,
    semigroupBackendAnalysis,
    monoidBackendAnalysis
};
//# sourceMappingURL=index.js.map
